### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by tomasmcz** [tomasmcz/mtm16-gpu#1]
- [x] write to Marcin (Theano, Jupyter) and David (Theano)
- [ ] run something on EC2 and write instructions for the wiki
  - [x] how to use the voucher
  - [x] how to run a server
  - [x] how to run a GPU instance
  - [ ] how to check your balance
- [ ] write .bashrc for ufal computers?
- [ ] jsou na merkuru kvóty?
- [x] check ufal SGE queue
- [ ] je nějaký způsob, jak rozumně používat Titan?
- [x] take a look at ulab GPUs
- [ ] copy this whole repo to SVN?
- [ ] iridium je na wiki _now unused_?
- [x] update instructions for ufal machines
- [ ] can you simply copy a virtualenv?
